### ISSUE TITLE
Have error with X-Figma

### ISSUE THREAD

**Issue by nikobeatz** [leadream/figma-icon-automation#18]
Hello!
I have an error while figma icon automation action doing a Figma action:
`
Run primer/figma-action@v1.0.0-alpha.2
/usr/bin/docker run --name e47de3a698a6704b6eb6a3695cd1f2288d_34ecf4 --label 5588e4 --workdir /github/workspace --rm -e FIGMA_FILE_URL -e FIGMA_TOKEN -e INPUT_ARGS -e HOME -e GITHUB_JOB -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_REPOSITORY_OWNER -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_RETENTION_DAYS -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_SERVER_URL -e GITHUB_API_URL -e GITHUB_GRAPHQL_URL -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e GITHUB_ACTION_REPOSITORY -e GITHUB_ACTION_REF -e GITHUB_PATH -e GITHUB_ENV -e RUNNER_OS -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/juuust-react-icon/juuust-react-icon":"/github/workspace" 5588e4:7de3a698a6704b6eb6a3695cd1f2288d format=svg outputDir=./src/
Exporting *** components`
__________
`(node:1) UnhandledPromiseRejectionWarning: Error: Error fetching components from Figma: TypeError [ERR_INVALID_CHAR]: Invalid character in header content ["X-Figma-Token"]
    at client.file.then.then.then.then.catch.error (/entrypoint.js:115:11)
    at process._tickCallback (internal/process/next_tick.js:68:7)
    at Function.Module.runMain (internal/modules/cjs/loader.js:834:11)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
(node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
(node:1) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
`
--------
sorry for this weird formatted text
i create all secrets and tokens
what i doing wrong?

**Comment by hallee9000** [comment]
@nikobeatz Sorry I'm not sure what happened. Do you have a repo in GitHub? If so I can help look into it from the action logs.
